export const REDDIT_GET_POSTS_START = "REDDIT/GET_POSTS_START"
export const REDDIT_GET_POSTS_SUCCEED = "REDDIT/GET_POSTS_SUCCEED"
export const REDDIT_GET_POSTS_FAIL = "REDDIT/GET_POSTS_FAIL"

export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
